version: '2'

services:
  app:
    build: ./app
    env_file: .env
    volumes:
      - ./app:/home/node/app
    ports:
      - "3000:3000"
    entrypoint:
      /home/node/app/entrypoint.sh
    ports:
      - "3001:3001"
